### ISSUE TITLE
Sourcemaps issue

### ISSUE THREAD

**Issue by timofei-iatsenko** [bluetech/ng-annotate-patched#1]
I found your from ng-annotate-loader discussion. I tried to use it with webpack2. 

My config is pretty clear (we use es5, but with import/export ecma features)

```js
  module: {
        rules: [
            {
                test: /\.js$/,
                exclude: /node_modules/,
                use: [
                    {
                        loader: 'ng-annotate-loader',
                        options: {
                            ngAnnotate: 'ng-annotate-patched',
                            sourcemap: true,
                        },
                    },
                ],
            },
```

When I enable this loader with this fork, i see a lot of skipped files in my sourcemaps. 
Without this fork source map file weights about 1800mb, with this ~380kb.

Looks like this lib produces corrupted sourcemaps on annotated files, and webpack excludes this sourcemaps from final bundle.

**Comment by bluetech** [comment]
I released a new version 1.6.0; do you mind trying it and see if it solves this problem?

I did not try to reproduce it yet; I just have a vague suspicion that this is caused by outdated dependencies, so I lazily committed ea230ec3ce5335e3f8366d29152bb4fff2ac951c. If this doesn't fix the problem, I'll have a proper look.

**Comment by timofei-iatsenko** [comment]
Actually I managed the problem. Problem in the loader. I don't know why it works normally with original version of ngAnnotate, but i'm already fixed this bug and about to create a pull request to loader repo.

**Comment by bluetech** [comment]
Great!

**Comment by timofei-iatsenko** [comment]
Just to reference: https://github.com/huston007/ng-annotate-loader/pull/41
