### ISSUE TITLE
Should not break on files that contain javascript '@' decorators

### ISSUE THREAD

**Issue by Maximaximum** [bluetech/ng-annotate-patched#10]
Currently, ng-annotate-patched fails with an error:
`Module build failed: error: couldn't process source due to parse error,Unexpected character '@'`, if the loaded file contains the '@' decorators (like `@NgModule() export class MyModule { }`).

It seems like it should not be a huge problem to solve? :)

**Comment by Maximaximum** [comment]
It seems like this can be resolved by simply including this acorn plugin: https://github.com/angelozerr/acorn-es7

But how do we do that? I've got no idea, any help would be really appreciated

**Comment by bluetech** [comment]
A previous PR added support for dynamic import using an acorn plugin: https://github.com/bluetech/ng-annotate-patched/pull/8

We can do the same for decorators - add support as an optional feature, as long as it's not in the standard itself. I hope those plugins are composable.

**Comment by Maximaximum** [comment]
I've found out that, in my use, case, it's ok to downgrade the code to es5, and use ng-annotate **after** that. So, this issue is not relevant for me anymore, sorry for bothering. Please feel free to close it

**Comment by bluetech** [comment]
This is what I do as well :) The reason this fork exists is to support `import`/`export` which webpack and friends keep even after compiling down to ES5.
