### ISSUE TITLE
Travis CI build should be updated to include Node 8

### ISSUE THREAD

**Issue by dmellstrom** [bluetech/ng-annotate-patched#16]
Node.js 6 is in EOL.
8 should possibly be considered the new minimum.

**Comment by bluetech** [comment]
If it causes any inconvenience, it shouldn't be a problem to bump. Otherwise I don't see a reason to - might as well keep it, maybe someone out there is using it. What do you think?

**Comment by dmellstrom** [comment]
On second thought, I agree that it might be good to leave in, just to maintain compatibility for older projects. Even if people shouldn't be encouraged to use node 6 for new projects at this time, it's fair to say that the concept of security EOL doesn't really apply to a frontend build system.

I would still like to update the travisfile to include versions 8, 10, and 11

**Comment by bluetech** [comment]
Sounds good to me. Though perhaps leave 11 out -- according to [this](https://nodejs.org/en/about/releases/) it is not supported any more. So the matrix will be

- minimal: 6
- active LTSs: 8, 10, 12
- latest: 12 (soon 13, according to the link)
