### ISSUE TITLE
parse error Unexpected token

### ISSUE THREAD

**Issue by jacobhub** [bluetech/ng-annotate-patched#19]
Hi I am getting parse error when adding async await. 
Does ng-annotate-patched support async await syntex ?

**Comment by bluetech** [comment]
It should work -- just added a test which verifies this: d0167c11f501c270bd1658a030acd8deeb7113cc

Please share the source file and version you are using.

**Comment by jacobhub** [comment]
you a right, it was a mistake in my code.
I was mistakenly still using gulp-ng-annotate
