### ISSUE TITLE
ngInject not work for class constructor

### ISSUE THREAD

**Issue by wizardnet972** [bluetech/ng-annotate-patched#22]
when I run `node app.js` I got no change in the class constructor where I write `ngInject`. why?

https://stackblitz.com/edit/js-2bmswj

**app.js**
```
const patched = require('ng-annotate-patched');

const content = `
import * as angular from 'angular';

export class BarService {
  name = 'bar';

  constructor() {
    'ngInject';

    console.log('in bar');
  }
}

export class FooService {
  name = 'foo';

  constructor(barService: BarService) {
    'ngInject';
    console.log('in foo service ctor', barService);
  }
}

const modulex = angular
  .module('foo', [])
  .service('barService', BarService)
  .service('fooService', FooService)
  .run((fooService) => {
    'ngInject';

    console.log({ fooService });
  }).name;

const bootstrapModuleName = angular.module('application.bootstrap', [modulex]).name;

angular.bootstrap(document.body, [bootstrapModuleName]);
`;
const a = patched(content, {});

console.log({ a });
```

The output as you can see doesn't do inject within the class constructor.

```
a: {
    src: '\n' +
      "import * as angular from 'angular';\n" +
      '\n' +
      'export class BarService {\n' +
      "  name = 'bar';\n" +
      '\n' +
      '  constructor() {\n' +
      "    'ngInject';\n" +
      '\n' +
      "    console.log('in bar');\n" +
      '  }\n' +
      '}\n' +
      '\n' +
      'export class FooService {\n' +
      "  name = 'foo';\n" +
      '\n' +
      '  constructor(barService: BarService) {\n' +
      "    'ngInject';\n" +
      "    console.log('in foo service ctor', barService);\n" +
      '  }\n' +
      '}\n' +
      '\n' +
      'const modulex = angular\n' +
      "  .module('foo', [])\n" +
      "  .service('barService', BarService)\n" +
      "  .service('fooService', FooService)\n" +
      '  .run((fooService) => {\n' +
      "    'ngInject';\n" +
      '\n' +
      '    console.log({ fooService });\n' +
      '  }).name;\n' +
      '\n' +
      "const bootstrapModuleName = angular.module('application.bootstrap', [modulex]).name;\n" +
      '\n' +
      'angular.bootstrap(document.body, [bootstrapModuleName]);\n'
  }
}
```

**Comment by bluetech** [comment]
`: BarService` is TypeScript syntax, which is not supported by ng-annotate - it expects TypeScript annotations to have been stripped beforehand.

**Comment by wizardnet972** [comment]
@bluetech I change `constructor(barService: BarService) {` to `constructor(barService) {`. not work.
I try to change to `constructor(BarService) {` still doesn't work.
After I remove the `: BarService` it's now `es6` code.

**Comment by bluetech** [comment]
Try `patched(content, {add: true});`

**Comment by wizardnet972** [comment]
@bluetech yes it's was helpful :)
But I have noticed if the `ngInject;` doesn't at the first line, it doesn't work.
The problem is typescript is transpile the `private` to `this....` in the first line and push the `ngInject`- which make the `ng-annotate-patched` to not work:

```
 constructor(barService) {
    this.barService = barService; //<--- generate by typescript
    'ngInject';
    console.log('in foo service ctor', barService);
  }
```
Not generate `$inject`.

original code:
```
 constructor(private barService: BarService) {
    'ngInject';
    console.log('in foo service ctor', barService);
  }
```

https://stackblitz.com/edit/js-2bmswj

**Comment by bluetech** [comment]
I suggest either avoiding the `constructor(private barService: BarService)` syntax (remove the `private` and declaring the field and doing the assignment manually), or to use the `/* @ngInject @/` comment form instead (you put it above the `constructor` line).

**Comment by wizardnet972** [comment]
@bluetech the comment solves the problem `/* @ngInject */`. but unfortunately, the typescript compiler remove comments. typescript transpile to es6. then I run the `ng-annotate-patched`. 

if you have another alternative solution to the comment I would really appriciate it

Thank you!

**Comment by bluetech** [comment]
In my experience, the typescript compiler (tsc) does not remove comments by default, though there is an option [`removeComments`](https://www.typescriptlang.org/tsconfig#removeComments) for this - maybe you set it?

Sorry, I have no other solutions.

**Comment by wizardnet972** [comment]
@bluetech I was able to preserve the comment and I put the comment at above the class line and it's work.

Thank you for your help and your time :))))
